# Стейдж сборки (Builder)
FROM eclipse-temurin:17-jdk-alpine AS builder

WORKDIR /app

# Шаг 1: Копируем только то, что нужно для загрузки Gradle
COPY gradlew .
COPY gradle/ gradle/
COPY build.gradle .
COPY settings.gradle .

# Шаг 2: Скачиваем Gradle (этот слой закэшируется)
# Флаг --no-daemon важен для Docker-контейнеров
RUN ./gradlew --version

# Шаг 3: Копируем исходный код
COPY src/ src/

# Шаг 4: Собираем проект (теперь Gradle уже на месте)
RUN ./gradlew clean build -x test

# Стейдж запуска (Final image)
FROM eclipse-temurin:17-jre-alpine

WORKDIR /app

# Создаем пользователя для безопасности (требование 2.1)
RUN addgroup -S nikitagrp && adduser -S nikita -G nikitagrp

# Копируем только готовый jar из первого стейджа
COPY --from=builder /app/build/libs/*.jar app_Nikita.jar

USER nikita

ENTRYPOINT ["java", "-jar", "app_Nikita.jar"]